### ISSUE TITLE
kernel build fails

### ISSUE THREAD

**Issue by fishpm-anu** [AdityaGarg8/mbp-16.x-ubuntu-kernel#17]
when building a new kernel as per "building yourself" it fails at the end with;
```
make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 2
make: *** [Makefile:1539: deb-pkg] Error 2
```
The system is a 2019 mac mini running Linux Mint 20.2.
Does something else need to be done for building on Mint?

**Comment by AdityaGarg8** [comment]
You need see the whole log to check where the error is. I cannot help you with this log.

**Comment by AdityaGarg8** [comment]
Even better, you can download a kernel from the releases.

**Comment by fishpm-anu** [comment]
> You need see the whole log to check where the error is. I cannot help you with this log.

the build doesn't produce a detailed log. how do I create one?

**Comment by AdityaGarg8** [comment]
I noticed there was a missing package named zstd causing compilation errors. Could you retry the script from the latest commit?

Also, during compiling, you have to have an eagle eye to notice any warning. Then only it's possible to diagnose the issue.
