### ISSUE TITLE
List zstd as depedency 

### ISSUE THREAD

**Issue by ddurdle** [AdityaGarg8/mbp-16.x-ubuntu-kernel#20]
zstd is not installed by default on Debian and your kernel images are using it.

dpkg-deb: error: archive '/tmp/headers.deb' uses unknown compression for member 
'control.tar.zst', giving up

**Comment by ddurdle** [comment]
Looks like a much bigger issue:

Debian’s dpkg package [doesn’t support zstd compression](https://bugs.debian.org/892664). It may support it in the future, but it doesn’t yet.

**Comment by AdityaGarg8** [comment]
Well there is a fork for the Debian version

https://github.com/andersfugmann/T2-Debian-Kernel

**Comment by AdityaGarg8** [comment]
Well since I have not received any response yet, I am closing this issue. You may reopen it if needed.
