### ISSUE TITLE
Possible to use disk encryption?

### ISSUE THREAD

**Issue by comminutus** [AdityaGarg8/mbp-16.x-ubuntu-kernel#21]
When installing Ubuntu, is it possible to add an encrypted disk volume in the partition editor and place the swap, root, and home partitions in the encrypted partition?  I tried it on a Mac Mini but not sure if I'm running into the Grub problem there or if it's because of the encryption.  I'm also going to try on a 2018 MacBook Pro.

**Comment by AdityaGarg8** [comment]
I haven't used encryption before but maybe https://wiki.t2linux.org/guides/dkms/#make-modules-load-on-early-boot or someone on the discord may help you.

**Comment by comminutus** [comment]
Loading the dkms module early worked. Thanks @AdityaGarg8 !
