### ISSUE TITLE
Touchbar does not show on restart; shows up only on full shutdown and start.

### ISSUE THREAD

**Issue by efoo99** [AdityaGarg8/mbp-16.x-ubuntu-kernel#26]
Updated fresh install of ubuntu 2.20-4 LTS with t2-ubuntu-kernel (5.15.74-t2) on macbookpro 15".
Touchbar shows up as expected on fresh start.
However on restart, touchbar does not show up.

**Comment by AdityaGarg8** [comment]
Do you happen to have done a force shutdown?

**Comment by AdityaGarg8** [comment]
Also, could you share your `lsusb` and `sudo dmesg | grep apple-ib` whenever you face this issue again.

**Comment by efoo99** [comment]
Two circumstances in summary:
1. System went into forced shutdown due to errant app. Two external displays connected via USB-C. First effective reboot does not show touchbar. After recovery, and full proper shutdown, touchbar reappears.
2. After proper startup, go to restart, after restart, touchbar appears. After shutdown and cold restart, touchbar does not appear. 2nd shutdown and restart, touchbar reappears.

**Comment by AdityaGarg8** [comment]
Well everytime you do a force shutdown, the touchbar won't work for the next boot, provided you do not boot into macOS.

If you boot into macOS after a force shutdown, then touchbar will work in subsequent boot of Linux.
