### ISSUE TITLE
External Thunderbolt NVMe storage not recognized on 6.0.10-t2-jammy

### ISSUE THREAD

**Issue by davidrozen76** [AdityaGarg8/mbp-16.x-ubuntu-kernel#30]
Hello!

When I connect a Thunderbolt 3 NVMe storage device, Ubuntu prompts to authorize the device. After authorization, the device shows as authorized & connected, but its volumes do not appear no in blkid, lsblk or fdisk.

No other informative information on dmesg.

Internal NVMe storage is working as expected (/dev/nvme0n1)

Tested against 2 different types of NVMe controllers.

When I boot 6.0.10-t2-jammy on non-mac, it works.

Help?

**Comment by AdityaGarg8** [comment]
Your kernel parameters must be having `pcie_ports=compat` as a kernel parameter.

Try the following:-

1. Replace `pcie_ports=compat` with `pcie_ports=auto`
2. Replace `pcie_ports=compat` with `pcie_ports=native`
3. Remove the kernel parameter.

Then share the results, whether it works in any if the cases or not.

**Comment by davidrozen76** [comment]
Removing the suggested kernel parameter solved the issue.

Cheers!
