### ISSUE TITLE
Invalid archive signature

### ISSUE THREAD

**Issue by RomanistHere** [AdityaGarg8/mbp-16.x-ubuntu-kernel#33]
![image](https://user-images.githubusercontent.com/49812531/208287977-d86c6c08-640a-4771-901c-38b4892fc649.png)

**Comment by AdityaGarg8** [comment]
I’ve pushed a fix. Upgrade your t2-kernel-script package using `apt upgrade`

**Comment by RomanistHere** [comment]
@AdityaGarg8 it works, thanks for fixing it so fast :+1:
