### ISSUE TITLE
The Checksums are Failling to verify. Error message attached below: 

### ISSUE THREAD

**Issue by ghost** [AdityaGarg8/mbp-16.x-ubuntu-kernel#38]
"Downloading new kernel v6.2.11-1

Downloading linux-headers-6.2.11-t2-lunar

######################################################################### 100.0%

Downloading linux-image-6.2.11-t2-lunar

######################################################################### 100.0%

Verifying checksums

Error: Failed to verify checksum of linux-headers-6.2.11-t2-lunar

Error: Failed to verify checksum of linux-image-6.2.11-t2-lunar
"

**Comment by AdityaGarg8** [comment]
We won’t be supporting Ubuntu lunar until the stable version is released

**Comment by ghost** [comment]
Gotcha, that makes far more sense. Thank you for letting me know! I will go ahead and compile my own kernel then! Again, thank you!!!
