### ISSUE TITLE
update_t2_kernel on focal points to v6.1.32-1 that does not exist

### ISSUE THREAD

**Issue by pkarashchenko** [AdityaGarg8/mbp-16.x-ubuntu-kernel#41]
Workaround-ed this by manually installing v6.1.31-1, but still it would be good if github can redirect to v6.1.31-1 for focal automatically.

**Comment by AdityaGarg8** [comment]
There have been issues in the GitHub CI, making me unable to compile a kernel for focal. If the issue persists, the script shall be modified to redirect to 6.1.31.

**Comment by AdityaGarg8** [comment]
Kernels for 20.04 have been started releasing again. You may try upgrading to the latest kernel 6.1.39-2 and if it works, then you may close this issue.
