### ISSUE TITLE
`update_t2_kernel` script needs to map Linux Mint `victoria` (beta 21.2 ISO) to `jammy` 

### ISSUE THREAD

**Issue by danielweck** [AdityaGarg8/mbp-16.x-ubuntu-kernel#42]
I patched my local `update_t2_kernel` and it seems to work fine :)

**Comment by danielweck** [comment]
Confirmed. All works well when adding a test for `victoria` in the script `update_t2_kernel` to map to `jammy`.

**Comment by danielweck** [comment]
Linux Mint Victoria announcement + ISO download links: https://blog.linuxmint.com/?p=4521

**Comment by AdityaGarg8** [comment]
Please open a PR to the script branch

**Comment by danielweck** [comment]
Thanks for pointing me to the `script` branch, there you go :)
https://github.com/t2linux/T2-Ubuntu-Kernel/pull/43

**Comment by danielweck** [comment]
Note to visitors interested in using the T2 kernels on Linux Mint: I had to edit the Grub params (added `nomodeset`) so my MacMini late-2018 could boot on the kernel v5 that ships with the official Mint ISO, but no need for that kernel param with the T2 v6 kernel.
