### ISSUE TITLE
release upgrade path not publicly documented

### ISSUE THREAD

**Issue by tpchuckles** [AdityaGarg8/mbp-16.x-ubuntu-kernel#44]
I have the basic question: should i "sudo do-release-upgrade" to go from, say, Kinetic to Lunar, _before or after_ installing the corresponding kernel from here?

I suspect the answer is somewhere in the discord channel (this won't have been the first time I wanted to know), but it ought to be included in the upgrade section of the readme

**Comment by lemmyg** [comment]
Im not sure if understand the question. 
`sudo do-release-upgrade` is just an ubuntu command to upgrade the distribution from kinetic  to lunar for example.
Once the upgrade has been finished,  you just need to run` update_t2_kernel` command to update the t2 kernel.

**Comment by tpchuckles** [comment]
right. do-release-upgrade upgrades ubuntu, and update_t2_kernel updates the kernel. but does order matter? (would it

**Comment by tpchuckles** [comment]
I see, thank you for the reply. I was updating my kernel by manually downloading and then using "sudo dpkg -i *.deb" to install them. in that scenario, the order isn't enforced (possible to download lunar kernel and install it before doing "do-release-upgrade"). 

that said, after running the ubuntu release upgrade, update_t2_kernel does _not_ seem to be updating to a lunar kernel. does it need to be installed manually, or does it not matter?
![2023-06-27 - 10-38-41](https://github.com/t2linux/T2-Ubuntu-Kernel/assets/8576442/570fe97d-9935-453e-a0dd-b518687632ac)

**Comment by AdityaGarg8** [comment]
You seem to have done just fine. No issues at all.
