### ISSUE TITLE
`latest` Git release tag currently on  `v6.1.53-1`, should be on `v6.5.2-1`?

### ISSUE THREAD

**Issue by danielweck** [AdityaGarg8/mbp-16.x-ubuntu-kernel#48]
https://github.com/t2linux/T2-Ubuntu-Kernel/releases

I'm currently on `6.4.11-1`, is it "safe" to replace with `6.5.2-1`? (I'm slightly confused by the release train, sorry :) 

`/usr/bin/update_t2_kernel` currently contains `use_lts=false` and `lts_version=6.1`.

FYI:

___
`dpkg --list | grep -i -E --color 'linux-image|linux-kernel' | grep '^ii'`
=>
`ii  linux-image-6.4.11-t2-jammy 6.4.11-1 amd64 Linux kernel, version 6.4.11-t2-jammy`
___
`uname -a`
=>
`Linux macmini 6.4.11-t2-jammy #1 SMP PREEMPT_DYNAMIC Thu Aug 17 03:24:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
___
`lsb_release -a`
=>
```
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.2
Release:	21.2
Codename:	victoria
```

**Comment by danielweck** [comment]
Related issue: https://github.com/t2linux/T2-Ubuntu-Kernel/issues/39

**Comment by AdityaGarg8** [comment]
The CI had some issue causing the latest release to change. I've changed it back to 6.5.2-1

Also, 6.5.3 shall be released soon.

**Comment by danielweck** [comment]
Thank you for your prompt reply, and for maintaining the T2 projects :)
