### ISSUE TITLE
Touchbar: /sys/class/input/*/device/fnmode: No such file or directory

### ISSUE THREAD

**Issue by Rom888** [AdityaGarg8/mbp-16.x-ubuntu-kernel#52]
After upgrading to the latest kernel 6.5.7-t2-jammy, I installed tiny-dfr and restarted ubuntu.
The touchbar is working, but if I run:
```
sudo touchbar
```
and press '1'
I got an error:
```
$ sudo touchbar
Select Touch Bar mode

0: Only show F1-F12
1: Show media and brightness controls, use the fn key to switch to F1-F12
2: Show F1-F12, use the fn key to switch to media and brightness controls
3: Only show media and brightness controls
4: Only show the escape key
1
Changing default mode ...
bash: line 1: /sys/class/input/*/device/fnmode: No such file or directory
```

**Comment by AdityaGarg8** [comment]
Fix this by running `sudo rm /usr/local/bin/touchbar; sudo rm /etc/modprobe.d/apple-tb.conf`

**Comment by Rom888** [comment]
Aditya, it works now, thank you!

I set up the default touchbar mode.
Is there any help on how to use other options?
For example, I see the --time option, but I don't see the time on the touchbar.

**Comment by AdityaGarg8** [comment]
Can you post a screenshot of your touchbar ?

**Comment by AdityaGarg8** [comment]
You also can share `cat /etc/tiny-dfr.conf`

**Comment by Rom888** [comment]
![20231018_113550](https://github.com/t2linux/T2-Ubuntu-Kernel/assets/36224737/08e2dcf2-6c23-45d7-9c6e-151dc16bb558)
![20231018_113558](https://github.com/t2linux/T2-Ubuntu-Kernel/assets/36224737/4720539d-9ea6-4564-bf4b-08868155b29a)

**Comment by AdityaGarg8** [comment]
The media controls + apps mode shows time

**Comment by AdityaGarg8** [comment]
You are using the media controls only mode

**Comment by Rom888** [comment]
```
$ cat /etc/tiny-dfr.conf
[ui]
primary_layer = "special"
secondary_layer = "function"
font = "sans-serif"
icon_theme = "tiny-dfr-icons"

[apps]
app_icon_theme = "tiny-dfr-icons"
app1_icon = "app1"
app2_icon = "app2"
app3_icon = "app3"
app4_icon = "app4"

[time]
use_24_hr = 1
```

**Comment by AdityaGarg8** [comment]
If you want time, use `sudo touchbar --mode` and instead of Media controls, choose media controls + apps

**Comment by Rom888** [comment]
Okay thanks!
It works and looks great!

**Comment by Rom888** [comment]
Is it possible to adjust the light level of the touchbar?

**Comment by AdityaGarg8** [comment]
Not yet, but I’ll add it to my todo list for this

**Comment by Rom888** [comment]
Thanks!
In the previous version, the touchbar disappeared after some time, is this possible now?

**Comment by AdityaGarg8** [comment]
Yeah it gets dim after 30 sec, disappears after another 30 sec

**Comment by AdityaGarg8** [comment]
I am closing this issue, if you have any other issue, please reopen this or create a new issue.

**Comment by stevezz3** [comment]
@AdityaGarg8 Hi, I have the exact same problem at the title describes. My touchbar shows media control buttons, but none of them are responsive. As I run `sudo touchbar --mode`, it prompts
```
Select Touch Bar mode

0: Only show F1-F12
1: Show media and brightness controls, use the fn key to switch to F1-F12
2: Show F1-F12, use the fn key to switch to media and brightness controls
3: Only show media and brightness controls
4: Only show the escape key
1
Changing default mode ...
bash: line 1: /sys/class/input/*/device/fnmode: No such file or directory
Done!
```
My setup: MacBookPro16,2
6.9.9-1-t2-jammy
Ubuntu 22.04.4 LTS

**Comment by AdityaGarg8** [comment]
> @AdityaGarg8 Hi, I have the exact same problem at the title describes. My touchbar shows media control buttons, but none of them are responsive. As I run `sudo touchbar --mode`, it prompts
> 
> ```
> Select Touch Bar mode
> 
> 0: Only show F1-F12
> 1: Show media and brightness controls, use the fn key to switch to F1-F12
> 2: Show F1-F12, use the fn key to switch to media and brightness controls
> 3: Only show media and brightness controls
> 4: Only show the escape key
> 1
> Changing default mode ...
> bash: line 1: /sys/class/input/*/device/fnmode: No such file or directory
> Done!
> ```
> 
> My setup: MacBookPro16,2 6.9.9-1-t2-jammy Ubuntu 22.04.4 LTS

Share

```
ls /usr/local/bin
```

**Comment by stevezz3** [comment]
When I run `ls /usr/local/bin`
```
ls: cannot access '/usr/local/bin': No such file or directory
```
and if I run `ls -l /usr/bin/touchbar`
```
-rwxr-xr-x 1 root root 27033 Jul 10 15:53 /usr/bin/touchbar
```

**Comment by AdityaGarg8** [comment]
> When I run `ls /usr/local/bin`
> 
> ```
> ls: cannot access '/usr/local/bin': No such file or directory
> ```
> 
> and if I run `ls -l /usr/bin/touchbar`
> 
> ```
> -rwxr-xr-x 1 root root 27033 Jul 10 15:53 /usr/bin/touchbar
> ```

Reinstall tiny-dfr

`sudo apt install --reinstall tiny-dfr`

**Comment by AdityaGarg8** [comment]
Restart your Mac after reinstalling

**Comment by stevezz3** [comment]
It works like a charm. Thank you very much!
