### ISSUE TITLE
Touchbar (tiny-dfr) doesn't start

### ISSUE THREAD

**Issue by aboulfad** [AdityaGarg8/mbp-16.x-ubuntu-kernel#54]
**Issue**
Touchbar (tiny-dfr) doesn't start because of numerous restarts & exits. Culprit seems to be related to `thread panic No backlight device found`. It worked only once but since I couldn't get it to work after numerous times of purging/reinstallation as per [instructions](https://wiki.t2linux.org/guides/postinstall/#setting-up-the-touch-bar).

**MBP Info**
MacBook Pro 2018, i7
Model ID: MacBookPro15,2
Controller Firmware version: 21P365
OS: Sonoma (14.0)

**T2Linux Info**
kernel: 6.5.7-t2
OS: Ubuntu 23.10 (Mantic Minotaur)

[tiny-dfr.log](https://github.com/t2linux/T2-Ubuntu-Kernel/files/13024881/tiny-dfr.log)

```
status tiny-dfr
× tiny-dfr.service - Tiny Apple silicon touch bar daemon
     Loaded: loaded (/etc/systemd/system/tiny-dfr.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-10-18 07:21:15 EDT; 6s ago
   Duration: 7ms
    Process: 2233 ExecStart=/usr/bin/tiny-dfr (code=exited, status=101)
   Main PID: 2233 (code=exited, status=101)
        CPU: 7ms

Oct 18 07:21:15 ubumbp systemd[1]: tiny-dfr.service: Scheduled restart job, restart counter is at 2.
Oct 18 07:21:15 ubumbp systemd[1]: Stopped tiny-dfr.service - Tiny Apple silicon touch bar daemon.
Oct 18 07:21:15 ubumbp systemd[1]: tiny-dfr.service: Start request repeated too quickly.
Oct 18 07:21:15 ubumbp systemd[1]: tiny-dfr.service: Failed with result 'exit-code'.
Oct 18 07:21:15 ubumbp systemd[1]: Failed to start tiny-dfr.service - Tiny Apple silicon touch bar daemon.
```

**Comment by AdityaGarg8** [comment]
Are you not able to cleanly shut down your Mac?

**Comment by AdityaGarg8** [comment]
Also share `lsusb`

**Comment by AdityaGarg8** [comment]
Share `dkms status` as well.

**Comment by AdityaGarg8** [comment]
Please clarify "numerous restarts and exits"

**Comment by AdityaGarg8** [comment]
> Moving issue to discord

**Comment by aboulfad** [comment]
1. I am able to cleanly shutdown my MBP from both Linux & Mac.
2. lsusb
```
lsusb
Bus 007 Device 008: ID 05ac:8102 Apple, Inc. Touch Bar Backlight
Bus 007 Device 007: ID 05ac:8302 Apple, Inc. Touch Bar Display
Bus 007 Device 006: ID 05ac:027b Apple, Inc. Apple Internal Keyboard / Trackpad
Bus 007 Device 005: ID 05ac:8103 Apple, Inc. Headset
Bus 007 Device 004: ID 05ac:8262 Apple, Inc. Ambient Light Sensor
Bus 007 Device 003: ID 05ac:8514 Apple, Inc. FaceTime HD Camera (Built-in)
Bus 007 Device 002: ID 05ac:8233 Apple, Inc. iBridge
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
3. `dkms status` returns nothing
4. I tried the sequence of install tiny-dfr, clean boot, few times but touch bar keeps exiting

**Comment by aboulfad** [comment]
After much great support from @AdityaGarg8 :heart: on #ubuntu discord channel, the solution was the following:
- ` sudo touchbar --switch` & restart may cleanup some residual bugs/issues,
- then redo the same command again to get the new touchbar design.

**Note**
The new advanced/design doesnt work with lid closure. It seems that the touchbar doesnt wake up upon lid open. The old design is immune to this issue.

Included photos of old vs new touchbar design.
**Old design**
![tb-old](https://github.com/t2linux/T2-Ubuntu-Kernel/assets/16640625/a433e19e-f5e8-4792-9e5e-4cc6f01a7f44)

**New design**
![tb-new](https://github.com/t2linux/T2-Ubuntu-Kernel/assets/16640625/0aa95d71-19e7-433f-8436-c59bd1b2b003)
