### ISSUE TITLE
update_t2_kernel memtest86+ error

### ISSUE THREAD

**Issue by yadu-tv** [AdityaGarg8/mbp-16.x-ubuntu-kernel#57]
Updating GRUB or using update-t2-kernel (LTS version) gives out the following error
![image](https://github.com/t2linux/T2-Ubuntu-Kernel/assets/32433876/ef27c345-9d2c-4536-add5-e12d20a4501d)

**Comment by AdityaGarg8** [comment]
This doesn't look like a bug. Is this affecting you in anyway?

**Comment by AdityaGarg8** [comment]
You also need to run `update_t2_kernel --remove-current` to remove the 6.5.7-t2 kernel otherwise grub will boot 6.5.7.

**Comment by yadu-tv** [comment]
The issue is that I am not able to update to the latest kernel. And also, I tried with the flags but it gives the same output

**Comment by AdityaGarg8** [comment]
memtest is not the issue, you are not uninstalling the 6.5.7 kernel, so it won't use the LTS kernel unless you remove the 6.5.7 kernel.

--remove-current will do that

Or just run `sudo apt remove linux-image-6.5.7-t2-jammy` amd manually install the LTS kernel by downloading the debs and mentioned in the readme

**Comment by yadu-tv** [comment]
I tried the steps and then tried restarting, now the whole system seems like broken. Will have to reinstall the OS again. 
None of the drivers work anymore, so I think the kernel is completely broken.

**Comment by AdityaGarg8** [comment]
What is broken?

**Comment by AdityaGarg8** [comment]
Did you install tiny-dfr before you switched to LTS?

**Comment by yadu-tv** [comment]
I just tried restarting, and I cannot login into the laptop. Keyboard, mouse, wifi, nothing is detected.

**Comment by AdityaGarg8** [comment]
Did you manually install the debs or use update_t2_kernel?

**Comment by AdityaGarg8** [comment]
> Did you install tiny-dfr before you switched to LTS?

And this too?

**Comment by yadu-tv** [comment]
I had tried manually yesterday. Also, i did not do tiny-dfr.

**Comment by AdityaGarg8** [comment]
You got an external keyboard and mouse?

**Comment by AdityaGarg8** [comment]
If yes, login and share `ls /boot`

**Comment by yadu-tv** [comment]
I have a meeting in 30 so right now i have to reinstall the OS (seems the fastest way to get back). But yes, I shall try to reproduce this again and let you know.

**Comment by AdityaGarg8** [comment]
> I had tried manually yesterday. Also, i did not do tiny-dfr.

Now did you try manually? There is no use installing manually without uninstalling 6.5.7.

And now you haven't installed manually, so you probably have completely uninstalled the T2 kernel.

**Comment by AdityaGarg8** [comment]
You basically have to manually install the kernel using an external keyboard/mouse and restart

**Comment by yadu-tv** [comment]
Gotcha. Manual installation takes an hour, I shall just reinstall the ISO file again
