### ISSUE TITLE
Correct kernel parameters pcie_ports=native or compat

### ISSUE THREAD

**Issue by Rom888** [AdityaGarg8/mbp-16.x-ubuntu-kernel#59]
I made fresh install of ubuntu-23.04-6.4.8-t2-lunar and then upgraded to the latest v6.5.9-1 kernel.

After the upgrade suspend doesn't work (macOs: Ventura 13.2) and Google Chrome sometimes freezes the entire system.

I also noticed that there is no pcie_ports=compat in the kernel parameters. Could this be the cause of the problems?
```
$ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-6.5.9-t2-lunar root=UUID=028e67b3-4f7b-4783-8315-a3fb634622ba ro pcie_ports=native intel_iommu=on iommu=pt quiet splash vt.handoff=7
```

machine:
```
macOs: Ventura 13.2

Ubuntu 23.04
6.5.9-t2-lunar

MacBookPro16.1
Intel Core i9 2.3g

hybrid graphics:
Intel UHD graphics 630
AMD radeon pro 5500M
```

**Comment by AdityaGarg8** [comment]
You need to share `journalctl -k`. You can a post it to pastebin.

**Comment by Rom888** [comment]
[journalctl.txt](https://github.com/t2linux/T2-Ubuntu-Kernel/files/13212653/journalctl.txt)

**Comment by AdityaGarg8** [comment]
Can you try turning off hybrid graphics?

**Comment by Rom888** [comment]
How can I do it?
I use iGPU only now.

**Comment by AdityaGarg8** [comment]
Remove apple-os-set

**Comment by AdityaGarg8** [comment]
It should be `sudo cp /boot/efi/efi/boot/bootx64_original.efi /boot/efi/efi/boot/bootx64.efi`

**Comment by AdityaGarg8** [comment]
And then restart

**Comment by Rom888** [comment]
Ok, should I keep it:
/etc/modprobe.d/apple-gmux.conf
with:
options apple-gmux force_igd=y
?

**Comment by AdityaGarg8** [comment]
You can remove that, although it shouldn't interfere much when apple-set-os is removed

**Comment by Rom888** [comment]
[journalctl-amd.txt](https://github.com/t2linux/T2-Ubuntu-Kernel/files/13212723/journalctl-amd.txt)

**Comment by AdityaGarg8** [comment]
What I meant was that if you are not using hybrid graphics, are you facing the issue you are facing rn?

**Comment by Rom888** [comment]
With AMD graphics even shutdown doesn't work.

**Comment by AdityaGarg8** [comment]
Are you using an external monitor/thunderbolt device?

**Comment by Rom888** [comment]
Not now, but I am going to use it.

**Comment by AdityaGarg8** [comment]
I'll see to this issue later.

**Comment by Rom888** [comment]
Only connected Type-C adapter, but without any monitor connected.

**Comment by Rom888** [comment]
I think I found the reason why Chrome freezes the system. Ubuntu uses iGPU:
```
$ glxinfo | grep "OpenGL renderer"
OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
```

But in the 'chrome://gpu' there is the following:
GL_RENDERER                     : ANGLE (AMD, Vulkan 1.3.238 (AMD Radeon Graphics (RADV NAVI14) (0x00007340)), radv-23.0.4)

It looks like Chrome uses amdGPU.
I haven't found how to switch Chrome to iGPU. ?

But after switching AMD GPU DPM from auto to low Chrome stopped to freeze the system.

Anyway, resuming after suspend still doesn't work correctly.

**Comment by AdityaGarg8** [comment]
If you right click on chrome and choose use discrete graphics card, does it use intel?

**Comment by Rom888** [comment]
I don't understand how can I 'click on chrome'?

**Comment by AdityaGarg8** [comment]
I said 'right click' on the chrome icon

**Comment by Rom888** [comment]
Oh, yes, sorry.
But there is no graphics card selection option on the Chrome icon.

**Comment by AdityaGarg8** [comment]
There have some significant changes to igpu. Can you test using the latest kernel and follow the new igpu guide @Rom888 ? You need to remove the apple-os-set bootloader

**Comment by Rom888** [comment]
Aditya, I read this new igpu guide. Could you please give an example how can I "Add apple_set_os as a kernel parameter".
Now I have: cat /proc/cmdline
```
BOOT_IMAGE=/boot/vmlinuz-6.5.9-t2-lunar root=UUID=028e67b3-4f7b-4783-8315-a3fb634622ba ro pcie_ports=native intel_iommu=on iommu=pt quiet splash vt.handoff=7
```
Should it be? :
```
... iommu=pt quiet splash vt.handoff=7 apple_set_os
```

**Comment by AdityaGarg8** [comment]
> Aditya, I read this new igpu guide. Could you please give an example how can I "Add apple_set_os as a kernel parameter". Now I have: cat /proc/cmdline
> 
> ```
> BOOT_IMAGE=/boot/vmlinuz-6.5.9-t2-lunar root=UUID=028e67b3-4f7b-4783-8315-a3fb634622ba ro pcie_ports=native intel_iommu=on iommu=pt quiet splash vt.handoff=7
> ```
> 
> Should it be? :
> 
> ```
> ... iommu=pt quiet splash vt.handoff=7 apple_set_os
> ```

Yes. Follow the Permanently Add a Kernel Boot Parameter  section of this guide https://wiki.ubuntu.com/Kernel/KernelBootParameters

**Comment by Rom888** [comment]
Should I install apple_set_os as described here?:
https://github.com/aa15032261/apple_set_os-loader#usage

I didn't find it in the latest igpu manual.

**Comment by AdityaGarg8** [comment]
No it's no longer needed

**Comment by AdityaGarg8** [comment]
Make sure you have the latest kernel (6.6.9) installed

**Comment by Rom888** [comment]
I have installed ubuntu lunar, is it okay?
I don't see this version of ubuntu here:
https://github.com/t2linux/T2-Ubuntu/releases

**Comment by AdityaGarg8** [comment]
The kernels are still maintained till Jan 25

**Comment by AdityaGarg8** [comment]
You need to run `update_t2_kernel`

**Comment by AdityaGarg8** [comment]
https://github.com/t2linux/T2-Ubuntu-Kernel

**Comment by macmanjpd** [comment]
where is this "new" IGPU guide?

**Comment by AdityaGarg8** [comment]
> where is this "new" IGPU guide?

https://wiki.t2linux.org/guides/hybrid-graphics/

**Comment by AdityaGarg8** [comment]
Issue shall be closed due to lack of activity after 24hrs. If you wanna keep it open, reply within 24hrs.

**Comment by Rom888** [comment]
Aditya, thanks for support!
My plan was to upgrade my current system to Ubuntu 23.10 and test it there.
I am going to do it and let you know the results.

**Comment by Rom888** [comment]
I finally did a fresh install of T2-Ubuntu 23.10

'apple_set_os' works fine as a kernel parameter.

Ubuntu uses iGPU.

chrome://gpu shows that it uses iGPU too:
GL_RENDERER : ANGLE (Intel, Mesa ...)

I think we can close this issue, thank you!
