### ISSUE TITLE
New Touchbar driver from 6.5.7 not working

### ISSUE THREAD

**Issue by ZProLegend007** [AdityaGarg8/mbp-16.x-ubuntu-kernel#60]
Hi there, 

I have a MacBook Pro 2018 with touchbar and since the touchbar driver was changed it hasn't been working. I left it for a while hoping it would be fixed but it still doesn't work. Sometimes it shows up briefly while booting but then turns off once the keyboard backlight turns on.

I use the Debian kernel which is based off this. Thought I'd let you know.

Similar to this issue here https://github.com/t2linux/T2-Ubuntu-Kernel/issues/56

Running `tiny-dfr` gives a glibc error stating it needs GLIBC_2.32, GLIBC_2.33 and GLIBC_2.34.

**Comment by AdityaGarg8** [comment]
Looks like you need to compile it manually on debian

**Comment by AdityaGarg8** [comment]
If you do not want the newer touchbar though, you can revert to the older driver by running `sudo touchbar --switch` and restarting

**Comment by DamianNiolet** [comment]
> Hi there,
> 
> I have a MacBook Pro 2018 with touchbar and since the touchbar driver was changed it hasn't been working. I left it for a while hoping it would be fixed but it still doesn't work. Sometimes it shows up briefly while booting but then turns off once the keyboard backlight turns on.
> 
> I use the Debian kernel which is based off this. Thought I'd let you know.
> 
> Similar to this issue here #56
> 
> Running `tiny-dfr` gives a glibc error stating it needs GLIBC_2.32, GLIBC_2.33 and GLIBC_2.34.

Heya, Zac.  I had to reinstall Ubuntu then do the following commands:
- sudo apt update
- sudo apt install linux-apfs
- sudo apt install tiny-dfr
@AdityaGarg8 helped me with this on discord.

**Comment by AdityaGarg8** [comment]
Zac is using Debian, not Ubuntu. Also, linux-apfs is not related to tiny-dfr

**Comment by DamianNiolet** [comment]
> Zac is using Debian, not Ubuntu. Also, linux-apfs is not related to tiny-dfr

Ahh, well, all I know is the devices didn’t show up with lsusb until I did install-apfs, but then the touchbar didn’t work until installing tiny-dfr.

**Comment by ZProLegend007** [comment]
I will mention that neither the new or old touchbar modes worked. I will try and manually compiling, thanks.

**Comment by AdityaGarg8** [comment]
> I will mention that neither the new or old touchbar modes worked. I will try and manually compiling, thanks.

What's `lsusb`

**Comment by ZProLegend007** [comment]
```
Bus 007 Device 008: ID 05ac:8102 Apple, Inc. Touch Bar Backlight
Bus 007 Device 007: ID 05ac:8302 Apple, Inc. Touch Bar Display
Bus 007 Device 006: ID 05ac:027b Apple, Inc. Apple Internal Keyboard / Trackpad
Bus 007 Device 005: ID 05ac:8103 Apple, Inc. Headset
Bus 007 Device 004: ID 05ac:8262 Apple, Inc. Ambient Light Sensor
Bus 007 Device 003: ID 05ac:8514 Apple, Inc. FaceTime HD Camera (Built-in)
Bus 007 Device 002: ID 05ac:8233 Apple, Inc. Apple T2 Controller
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

It may be worth mentioning I have GLIBC_2.31 installed.

[dmesg.txt](https://github.com/t2linux/T2-Ubuntu-Kernel/files/13433485/dmesg.txt)

**Comment by AdityaGarg8** [comment]
```
sudo apt remove tiny-dfr
sudo apt install apple-touchbar
sudo modprobe apple-touchbar
```

**Comment by ZProLegend007** [comment]
```
z@FlintLockwood:~$ sudo apt install apple-touchbar
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  apple-touchbar
0 to upgrade, 1 to newly install, 0 to remove and 4 not to upgrade.
Need to get 35.4 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://adityagarg8.github.io/t2-ubuntu-repo ./ apple-touchbar 0.1.1 [35.4 kB]
Fetched 35.4 kB in 1s (52.3 kB/s)         
Selecting previously unselected package apple-touchbar.
(Reading database ... 296542 files and directories currently installed.)
Preparing to unpack .../apple-touchbar_0.1.1_amd64.deb ...
Unpacking apple-touchbar (0.1.1) ...
Setting up apple-touchbar (0.1.1) ...

Creating symlink /var/lib/dkms/apple-touchbar/0.1/source ->
                 /usr/src/apple-touchbar-0.1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=6.6.1-t2...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.6.1-t2 (x86_64)
Consult /var/lib/dkms/apple-touchbar/0.1/build/make.log for more information.
chmod: cannot access '/usr/local/bin/touchbar': No such file or directory
chown: cannot access '/usr/local/bin/touchbar': No such file or directory
Run "sudo touchbar" to change the default Touch Bar mode
z@FlintLockwood:~$ sudo modprobe apple-touchbar
modprobe: FATAL: Module apple-touchbar not found in directory /lib/modules/6.6.1-t2

z@FlintLockwood:~$ cat /var/lib/dkms/apple-touchbar/0.1/build/make.log
DKMS make.log for apple-touchbar-0.1 for kernel 6.6.1-t2 (x86_64)
Wed 22 Nov 2023 12:22:55 AWST
make -C /lib/modules/6.6.1-t2/build M=/var/lib/dkms/apple-touchbar/0.1/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.6.1-t2'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Debian 13.2.0-6) 13.2.0
  You are using:           gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
  CC [M]  /var/lib/dkms/apple-touchbar/0.1/build/apple-ibridge.o
  CC [M]  /var/lib/dkms/apple-touchbar/0.1/build/apple-touchbar.o
  CC [M]  /var/lib/dkms/apple-touchbar/0.1/build/hid-apple-magic-backlight.o
gcc: error: unrecognized command line option ‘-mharden-sls=all’
gcc: error: unrecognized command line option ‘-mharden-sls=all’
gcc: error: unrecognized command line option ‘-mharden-sls=all’
gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/apple-touchbar/0.1/build/apple-ibridge.o] Error 1
make[3]: *** Waiting for unfinished jobs....
gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/apple-touchbar/0.1/build/apple-touchbar.o] Error 1
gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/apple-touchbar/0.1/build/hid-apple-magic-backlight.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.6.1-t2/Makefile:1913: /var/lib/dkms/apple-touchbar/0.1/build] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.6.1-t2'
make: *** [Makefile:13: all] Error 2

```

**Comment by AdityaGarg8** [comment]
Hmm, remove apple-touchbar then. Try compiling tiny-dfr yourself

**Comment by ZProLegend007** [comment]
Tiny dfr is having issues compiling. dkms really doesn't like me.

```
z@FlintLockwood:~/tinydfr/tiny-dfr$ cargo build
    Updating crates.io index
  Downloaded bitflags v1.3.2
  Downloaded cfg-if v1.0.0
  Downloaded getrandom v0.2.10
  Downloaded derive_more v0.99.17
  Downloaded data-url v0.3.0
  Downloaded byteorder v1.4.3
  Downloaded drm-fourcc v2.2.0
  Downloaded crossbeam-deque v0.8.3
  Downloaded crossbeam-utils v0.8.16
  Downloaded memchr v2.6.3
  Downloaded rand_core v0.6.4
  Downloaded rayon-core v1.11.0
  Downloaded scopeguard v1.2.0
  Downloaded safe_arch v0.7.1
  Downloaded autocfg v1.1.0
  Downloaded approx v0.5.1
  Downloaded aho-corasick v1.0.5
  Downloaded cssparser-macros v0.6.1
  Downloaded futures-io v0.3.28
  Downloaded form_urlencoded v1.2.0
  Downloaded bytemuck v1.14.0
  Downloaded futures-macro v0.3.28
  Downloaded cssparser v0.29.6
  Downloaded cast v0.3.0
  Downloaded equivalent v1.0.1
  Downloaded futures-task v0.3.28
  Downloaded either v1.9.0
  Downloaded gdk-pixbuf-sys v0.18.0
  Downloaded dtoa v1.0.9
  Downloaded float-cmp v0.9.0
  Downloaded getrandom v0.1.16
  Downloaded futf v0.1.5
  Downloaded dtoa-short v0.3.4
  Downloaded futures-util v0.3.28
  Downloaded futures-executor v0.3.28
  Downloaded gdk-pixbuf v0.18.0
  Downloaded anyhow v1.0.75
  Downloaded cfg-expr v0.15.5
  Downloaded gio-sys v0.18.1
  Downloaded convert_case v0.4.0
  Downloaded bitflags v2.4.0
  Downloaded crossbeam-channel v0.5.8
  Downloaded gobject-sys v0.18.0
  Downloaded futures-core v0.3.28
  Downloaded bytemuck_derive v1.5.0
  Downloaded glib-sys v0.18.1
  Downloaded itoa v1.0.9
  Downloaded io-lifetimes v1.0.11
  Downloaded matches v0.1.10
  Downloaded memoffset v0.7.1
  Downloaded lazy_static v1.4.0
  Downloaded num-integer v0.1.45
  Downloaded nalgebra-macros v0.2.1
  Downloaded precomputed-hash v0.1.1
  Downloaded nodrop v0.1.14
  Downloaded pin-utils v0.1.0
  Downloaded phf_shared v0.10.0
  Downloaded phf_macros v0.10.0
  Downloaded lock_api v0.4.10
  Downloaded new_debug_unreachable v1.0.4
  Downloaded num_cpus v1.16.0
  Downloaded markup5ever v0.11.0
  Downloaded memoffset v0.9.0
  Downloaded mac v0.1.1
  Downloaded phf v0.10.1
  Downloaded heck v0.4.1
  Downloaded proc-macro-error-attr v1.0.4
  Downloaded phf_codegen v0.10.0
  Downloaded phf_generator v0.10.0
  Downloaded percent-encoding v2.3.0
  Downloaded pkg-config v0.3.27
  Downloaded locale_config v0.3.0
  Downloaded num-traits v0.2.16
  Downloaded num-complex v0.4.4
  Downloaded language-tags v0.3.2
  Downloaded rand_core v0.5.1
  Downloaded proc-macro-crate v1.3.1
  Downloaded rand_chacha v0.2.2
  Downloaded quote v1.0.33
  Downloaded rand_chacha v0.3.1
  Downloaded num-rational v0.4.1
  Downloaded paste v1.0.14
  Downloaded proc-macro-hack v0.5.20+deprecated
  Downloaded parking_lot_core v0.9.8
  Downloaded pango-sys v0.18.0
  Downloaded once_cell v1.18.0
  Downloaded parking_lot v0.12.1
  Downloaded ppv-lite86 v0.2.17
  Downloaded pango v0.18.0
  Downloaded log v0.4.20
  Downloaded pin-project-lite v0.2.13
  Downloaded futures-channel v0.3.28
  Downloaded proc-macro2 v1.0.66
  Downloaded proc-macro-error v1.0.4
  Downloaded indexmap v2.0.0
  Downloaded matrixmultiply v0.3.7
  Downloaded rawpointer v0.2.1
  Downloaded crossbeam-epoch v0.9.15
  Downloaded serde_spanned v0.6.4
  Downloaded semver v1.0.18
  Downloaded cc v1.0.83
  Downloaded stable_deref_trait v1.2.0
  Downloaded string_cache_codegen v0.5.2
  Downloaded tinyvec_macros v0.1.1
  Downloaded siphasher v0.3.11
  Downloaded rustc_version v0.4.0
  Downloaded rand v0.8.5
  Downloaded thiserror v1.0.48
  Downloaded rgb v0.8.36
  Downloaded rctree v0.5.0
  Downloaded toml_datetime v0.6.5
  Downloaded string_cache v0.8.7
  Downloaded udev v0.7.0
  Downloaded version-compare v0.1.1
  Downloaded version_check v0.9.4
  Downloaded utf-8 v0.7.6
  Downloaded system-deps v6.1.1
  Downloaded selectors v0.24.0
  Downloaded smallvec v1.11.0
  Downloaded tendril v0.4.3
  Downloaded thiserror-impl v1.0.48
  Downloaded slab v0.4.9
  Downloaded target-lexicon v0.12.11
  Downloaded simba v0.8.1
  Downloaded serde_derive v1.0.188
  Downloaded unicode-ident v1.0.11
  Downloaded typenum v1.16.0
  Downloaded tinyvec v1.6.0
  Downloaded xml5ever v0.17.0
  Downloaded unicode-bidi v0.3.13
  Downloaded toml v0.7.8
  Downloaded toml v0.8.8
  Downloaded drm-ffi v0.6.0
  Downloaded phf_shared v0.8.0
  Downloaded fxhash v0.2.1
  Downloaded itertools v0.11.0
  Downloaded serde v1.0.188
  Downloaded rand_pcg v0.2.1
  Downloaded rand v0.7.3
  Downloaded cairo-sys-rs v0.18.0
  Downloaded phf_generator v0.8.0
  Downloaded phf v0.8.0
  Downloaded phf_codegen v0.8.0
  Downloaded pangocairo v0.18.0
  Downloaded pangocairo-sys v0.18.0
  Downloaded wide v0.7.11
  Downloaded hashbrown v0.14.0
  Downloaded url v2.4.1
  Downloaded privdrop v0.5.4
  Downloaded servo_arc v0.2.0
  Downloaded libudev-sys v0.1.4
  Downloaded toml_edit v0.19.15
  Downloaded input-linux-sys v0.8.0
  Downloaded input v0.8.3
  Downloaded toml_edit v0.21.0
  Downloaded drm-sys v0.5.0
  Downloaded cairo-rs v0.18.0
  Downloaded glib-macros v0.18.0
  Downloaded input-linux v0.6.0
  Downloaded drm v0.10.0
  Downloaded idna v0.4.0
  Downloaded unicode-normalization v0.1.22
  Downloaded winnow v0.5.15
  Downloaded rayon v1.7.0
  Downloaded freetype-rs v0.32.0
  Downloaded nix v0.26.4
  Downloaded nix v0.27.1
  Downloaded syn v1.0.109
  Downloaded gio v0.18.1
  Downloaded syn v2.0.32
  Downloaded regex v1.9.5
  Downloaded nalgebra v0.32.3
  Downloaded glib v0.18.1
  Downloaded regex-syntax v0.7.5
  Downloaded librsvg v2.56.92
  Downloaded libc v0.2.147
  Downloaded regex-automata v0.3.8
  Downloaded input-sys v1.17.0
  Downloaded encoding_rs v0.8.33
  Downloaded freetype-sys v0.17.0
  Downloaded 180 crates (16.1 MB) in 7.59s (largest was `freetype-sys` at 3.8 MB)
error: package `glib-sys v0.18.1` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.66.1
Either upgrade to rustc 1.70 or newer, or use
cargo update -p glib-sys@0.18.1 --precise ver
where `ver` is the latest version of `glib-sys` supporting rustc 1.66.1

```

**Comment by AdityaGarg8** [comment]
Install rust from here: https://www.rust-lang.org/tools/install

You need to close your terminal and open a new window after running this.

**Comment by ZProLegend007** [comment]
Hmm

```
  cargo:warning=`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "pango" "pango >= 1.46"` did not exit successfully: exit status: 1
  error: could not find system library 'pango' required by the 'pango-sys' crate

  --- stderr
  Requested 'pango >= 1.46' but version of Pango is 1.44.7

warning: build failed, waiting for other jobs to finish...
```

**Comment by AdityaGarg8** [comment]
Thats probably the reason Ubuntu compiled tiny-dfr isn't working. You can try decreasing the version of pango in cargo.toml

**Comment by ZProLegend007** [comment]
There isn't a pango dependency shown in cargo.toml.

**Comment by AdityaGarg8** [comment]
Sorry I meant cairo

**Comment by ZProLegend007** [comment]
There is no cairo either. There is a cairo-rs but changing that version has no effect.

**Comment by AdityaGarg8** [comment]
Is it possible to get a newer version pango?

**Comment by ZProLegend007** [comment]
Thats what I'm trying to figure out.

**Comment by ZProLegend007** [comment]
I can't seem to find a solution... any other ideas?

**Comment by AdityaGarg8** [comment]
> z@FlintLockwood:~$ sudo apt install apple-touchbar
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following NEW packages will be installed:
>   apple-touchbar
> 0 to upgrade, 1 to newly install, 0 to remove and 4 not to upgrade.
> Need to get 35.4 kB of archives.
> After this operation, 0 B of additional disk space will be used.
> Get:1 https://adityagarg8.github.io/t2-ubuntu-repo ./ apple-touchbar 0.1.1 [35.4 kB]
> Fetched 35.4 kB in 1s (52.3 kB/s)         
> Selecting previously unselected package apple-touchbar.
> (Reading database ... 296542 files and directories currently installed.)
> Preparing to unpack .../apple-touchbar_0.1.1_amd64.deb ...
> Unpacking apple-touchbar (0.1.1) ...
> Setting up apple-touchbar (0.1.1) ...
> 
> Creating symlink /var/lib/dkms/apple-touchbar/0.1/source ->
>                  /usr/src/apple-touchbar-0.1
> 
> DKMS: add completed.
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area...
> make -j8 KERNELRELEASE=6.6.1-t2...(bad exit status: 2)
> Error! Bad return status for module build on kernel: 6.6.1-t2 (x86_64)
> Consult /var/lib/dkms/apple-touchbar/0.1/build/make.log for more information.
> chmod: cannot access '/usr/local/bin/touchbar': No such file or directory
> chown: cannot access '/usr/local/bin/touchbar': No such file or directory
> Run "sudo touchbar" to change the default Touch Bar mode
> z@FlintLockwood:~$ sudo modprobe apple-touchbar
> modprobe: FATAL: Module apple-touchbar not found in directory /lib/modules/6.6.1-t2
> 
> z@FlintLockwood:~$ cat /var/lib/dkms/apple-touchbar/0.1/build/make.log

what does this file show?

> DKMS make.log for apple-touchbar-0.1 for kernel 6.6.1-t2 (x86_64)
> Wed 22 Nov 2023 12:22:55 AWST
> make -C /lib/modules/6.6.1-t2/build M=/var/lib/dkms/apple-touchbar/0.1/build modules
> make[1]: Entering directory '/usr/src/linux-headers-6.6.1-t2'
> warning: the compiler differs from the one used to build the kernel
>   The kernel was built by: gcc (Debian 13.2.0-6) 13.2.0
>   You are using:           gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

Are you using Ubuntu or debian?

>   CC [M]  /var/lib/dkms/apple-touchbar/0.1/build/apple-ibridge.o
>   CC [M]  /var/lib/dkms/apple-touchbar/0.1/build/apple-touchbar.o
>   CC [M]  /var/lib/dkms/apple-touchbar/0.1/build/hid-apple-magic-backlight.o
> gcc: error: unrecognized command line option ‘-mharden-sls=all’
> gcc: error: unrecognized command line option ‘-mharden-sls=all’
> gcc: error: unrecognized command line option ‘-mharden-sls=all’
> gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
> make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/apple-touchbar/0.1/build/apple-ibridge.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
> make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/apple-touchbar/0.1/build/apple-touchbar.o] Error 1
> gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
> make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/apple-touchbar/0.1/build/hid-apple-magic-backlight.o] Error 1
> make[2]: *** [/usr/src/linux-headers-6.6.1-t2/Makefile:1913: /var/lib/dkms/apple-touchbar/0.1/build] Error 2
> make[1]: *** [Makefile:234: __sub-make] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-6.6.1-t2'
> make: *** [Makefile:13: all] Error 2

**Comment by ZProLegend007** [comment]
I'm using ZorinOS and Kali which are both Debian based. These outputs are all from ZorinOS.

And the output is the cat of that file.

**Comment by AdityaGarg8** [comment]
If you are using ZorinOS, you need to use kernel from T2-Ubuntu-Kernel, not T2-Debian-Kernel

**Comment by ZProLegend007** [comment]
After corrupting my old Zorin install I have re-installed with the Ubuntu kernel but the touchbar still doesn't work. Same glibc error. It's worth mentioning that kali doesn't have touchbar either.

**Comment by AdityaGarg8** [comment]
> After corrupting my old Zorin install I have re-installed with the Ubuntu kernel but the touchbar still doesn't work. Same glibc error. It's worth mentioning that kali doesn't have touchbar either.

What Ubuntu kernel have you used? I cannot help much with Kali, you'll have to mess around with the rust code to support the older version of build tools in your Kali installation.

**Comment by ZProLegend007** [comment]
It is using the jammy kernel. Zorin is built on focal though... 20.04. It acts the same as the debian kernel. It is odd though how both kernels and OSs stopped working at the same time. It must be the same issue.

**Comment by AdityaGarg8** [comment]
You should use the focal kernel, it is available in the LTS 6.1.x release.

**Comment by AdityaGarg8** [comment]
Also remove tiny-dfr as the 6.1.x release has the older touchbar driver, that does not need tiny-dfr

**Comment by ZProLegend007** [comment]
Alright, I assume I should intall the LTS kernel script then. I will do so and check back.

**Comment by AdityaGarg8** [comment]
Use `update_t2_kernel --remove-current` with that script.

**Comment by ZProLegend007** [comment]
Finally got that done. After installing `apple-touchbar` the touchbar now works again, I will try installing the LTS kernel in Kali as well and see what happens. I believe once Zorin 17 is released it should have a newer GLIBC and then I can use the newer kernels.

**Comment by ZProLegend007** [comment]
I was also wondering @AdityaGarg8 if I could ask your advice for something rather off topic?

**Comment by AdityaGarg8** [comment]
I cannot guarantee I'll be able to answer anything off topic, but you can anyways ask

**Comment by ZProLegend007** [comment]
I have a fork of the brunch framework optimized for running chromeOS on macbooks. There are quite a few issues but the major one being audio. How would you go about adding support? As chromeOS uses alsa and detects the audio outputs fine. It can output out of the aux port with some tinkering but internal speakers (even though detected) don't work. Looking through a bunch of logs shows the audio server (CRAS - ChromeOS Audio Server, it's only alsa and this) has a segfault that causes it to crash when outputting to the internal speakers. This happens on all t2 Macs but not on older ones I believe. How would you go about troubleshooting it? Since theres no pulseaudio it makes things hard.

**Comment by AdityaGarg8** [comment]
> I have a fork of the brunch framework optimized for running chromeOS on macbooks. There are quite a few issues but the major one being audio. How would you go about adding support? As chromeOS uses alsa and detects the audio outputs fine. It can output out of the aux port with some tinkering but internal speakers (even though detected) don't work. Looking through a bunch of logs shows the audio server (CRAS - ChromeOS Audio Server, it's only alsa and this) has a segfault that causes it to crash when outputting to the internal speakers. This happens on all t2 Macs but not on older ones I believe. How would you go about troubleshooting it? Since theres no pulseaudio it makes things hard.

I'm sorry, I don't have much idea in this aspect. You can ask in the discord server.

**Comment by ZProLegend007** [comment]
Update from kali, I know this is debian but I think you might be able to help. Running tiny-dfr now shows this.

```
thread 'main' panicked at src/main.rs:647:43:
called `Result::unwrap()` on an `Err` value: No touchbar device found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by AdityaGarg8** [comment]
What's `lsusb`

Also, what fork have you used to compile. Did you add the udev rules and systemd service?

**Comment by AdityaGarg8** [comment]
Inactive issue. Kindly respond within 24hrs or shall be considered fixed.
