### ISSUE TITLE
Bluetooth not working since kernel version 6.5.* 

### ISSUE THREAD

**Issue by rydymth** [AdityaGarg8/mbp-16.x-ubuntu-kernel#61]
Hi @AdityaGarg8 !
I have created this new issue!
Here is the [syslog](https://drive.google.com/file/d/1t18jjknE52VzR1nBlmV1Upt--QBaLfkB/view?usp=drive_link)
Had to upload on gdrive. It was too big for pastebin...

**Comment by AdityaGarg8** [comment]
It's invite only. Please make is readable to all

**Comment by rydymth** [comment]
Oh sorry about that!
Its done it should be readable now!

**Comment by AdityaGarg8** [comment]
@rydymth , can you test 6.6.8-2 when it gets released for Bluetooth?

**Comment by rydymth** [comment]
Yo boss IT WORKS!!!
BLUETOOTH IS WORKING YAY!!!
Connected to my headphones, everything is working just fine!
Here are the [dmesg](https://pastebin.com/fZX3Lqau) and  [journalctl](https://pastebin.com/gU1uDySE)

**Comment by AdityaGarg8** [comment]
Thanks for testing @rydymth

**Comment by rydymth** [comment]
Yes boss
Ill close this issue!

**Comment by AdityaGarg8** [comment]
@rydymth , the patch sent to fix Bluetooth was rejected and a new patch that may be accepted has been made. Can you please test kernel 6.6.8-3 to confirm whether the new patch works or not?

**Comment by rydymth** [comment]
Hello @AdityaGarg8 !
Yes boss it works just fine! Bluetooth works perfectly here are the [dmesg](https://pastebin.com/Jj1jLSYs) and [journalCtl](https://pastebin.com/hymzRm2E). Also tested with my headphones, works perfectly fine.
But there is this error during installation:

```
 * dkms: running auto installation service for kernel 6.6.8-t2-mantic
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/intel-platform-vsec-dkms/2023.20.0-21/source/dkms.conf does not exist.
 * dkms: autoinstall for kernel 6.6.8-t2-mantic                                                                                                   [fail]
run-parts: /etc/kernel/postinst.d/dkms exited with return code 4
```

But everything works nonetheless. No problem with bluetooth or anything.

**Comment by AdityaGarg8** [comment]
thanks
