### ISSUE TITLE
Unable to use firmware.sh on old macOS

### ISSUE THREAD

**Issue by irenatorosyan** [AdityaGarg8/mbp-16.x-ubuntu-kernel#62]
My computer is running macOS Mojave Version 10.14.6. Unfortunately, as I already partitioned my disk for Ubuntu, I am unable to update to later versions of macOS to be able to run the script. I am not sure if this is of any help, but I also have a mac on M2 chip running macOS Sonoma. Is there a way to use the arm computer or somehow run the script on older version of macOS?

**Comment by AdityaGarg8** [comment]
I asked you to report to kernel.org, not this repo

**Comment by AdityaGarg8** [comment]
You need to email

**Comment by irenatorosyan** [comment]
Sorry for the misunderstanding, thank you
