### ISSUE TITLE
Failed to verify checksum

### ISSUE THREAD

**Issue by codingnooob** [AdityaGarg8/mbp-16.x-ubuntu-kernel#64]
Hi, when I tried to `update_t2_kernel` to the latest version (v6.7.1-1), I get that it failed to verify the checksum. I'm using Linux Mint 21.3 (Virginia).

**Comment by codingnooob** [comment]
#43

**Comment by codingnooob** [comment]
#43

**Comment by AdityaGarg8** [comment]
Send a screenshot

**Comment by codingnooob** [comment]
![Screenshot from 2024-01-23 08-48-19](https://github.com/t2linux/T2-Ubuntu-Kernel/assets/66186626/6824ce97-8ab3-4e9a-b24b-fb9df8d510c9)

**Comment by AdityaGarg8** [comment]
I've pushed a fix. Try installing `t2-kernel-script` again.

**Comment by codingnooob** [comment]
Doing it via `update_t2_kernel` didn't work. Do you mean I have to do a full reinstallation?
EDIT: Doing `sudo apt reinstall t2-kernel-script` didn't work either

**Comment by AdityaGarg8** [comment]
What's `apt list --installed | grep t2-kernel-script`

And if you run update_t2_kernel, is it still showing virginita or has it changed to jammy?

**Comment by codingnooob** [comment]
I just reinstalled it manually and now it's updated successfully.

It's showing `t2-kernel-script/unknown`, presumably because I downloaded the amd64 deb files and then installed them from there. 

Anyways, thank you for the assistance!
