### ISSUE TITLE
Using tinydfr touchbar disables keyboard and touchpad

### ISSUE THREAD

**Issue by ZProLegend007** [AdityaGarg8/mbp-16.x-ubuntu-kernel#65]
Hello, I am using ZorinOS 17 which now supports the latest t2 ubuntu kernel.

When using the new tinydfr touchbar (at first it worked wonderfully) when booting the touchbar becomes a touchscreen device for the middle of the screen, the screen flickers about three times (doesn't happen normally) and then loads the login screen. However at that point the keyboard and touchpad are disabled. I can click the middle of the touchbar (which is blank) to click my user on the screen but from that point nothing else is clickable. This also triggers the OSK.

Doing a force restart and booting again fixes the issue (for that boot because the touchbar is hidden from the force restart) but there is no touchbar. As soon as the touchbar returns on the next boot the problem persists. 

It works fine with the simple touchbar drivers.

Help would be appreciated fixing!

**Comment by AdityaGarg8** [comment]
I've noticed a lot of zorin os users facing issues with tiny-dfr. If you want just the media controls and F keys, there is not much difference between simple and tiny-dfr. If you want customised touchbar, try compiling tiny-dfr yourself on Zorin OS.
