### ISSUE TITLE
Discrepancy Between Kernel Versions in Ubuntu 24.04 LTS Repository and Installation

### ISSUE THREAD

**Issue by maximus-sallam** [AdityaGarg8/mbp-16.x-ubuntu-kernel#88]
I've noticed an issue regarding the kernel versions for Ubuntu 24.04 LTS that I wanted to bring to your attention. The T2 kernel currently available through the repository is based on version 6.6.32. However, the kernel that came installed with Ubuntu 24.04 LTS is version 6.8.0.

Upon checking kernel.org, I observed that 6.6.32 is the latest LTS release. This raises a couple of questions: 

Why is there a discrepancy between the kernel version in the repository and the one included with the Ubuntu installation? 

Additionally, I'm curious to know the rationale behind using the latest version from kernel.org in the repository rather than the version that ships with Ubuntu.

Thank you for your time and assistance in clarifying these points. I look forward to your response.

**Comment by AdityaGarg8** [comment]
> I've noticed an issue regarding the kernel versions for Ubuntu 24.04 LTS that I wanted to bring to your attention. The T2 kernel currently available through the repository is based on version 6.6.32. However, the kernel that came installed with Ubuntu 24.04 LTS is version 6.8.0.
> 

Came installed with my T2-Ubuntu ISO or the official ISO?

> Upon checking kernel.org, I observed that 6.6.32 is the latest LTS release. This raises a couple of questions:
> 
> Why is there a discrepancy between the kernel version in the repository and the one included with the Ubuntu installation?
> 

I don't understand what discrepancy are you talking about? I have provided the option of using both the latest mainline kernel, which currently is 6.9.2 as well as the latest LTS, which is 6.6.62. Please clarify your doubt.

> Additionally, I'm curious to know the rationale behind using the latest version from kernel.org in the repository rather than the version that ships with Ubuntu.
> 

1. There is no difference in terms of performance on T2 Macs if you use the kernels provided by ubuntu.
2.  Hard to maintain, since there is not good documentation and they may change anything anytime.
3. Previously , the kernels were not uploaded on an apt repo. The apt repo has for kernels has been very recently made. Manual installation of the Ubuntu kernels was not easy for many users. Although, this is no longer the reason.

> Thank you for your time and assistance in clarifying these points. I look forward to your response.

**Comment by maximus-sallam** [comment]
Thank you for your reply. I appreciate you taking the time to answer my questions. I should have mentioned this is not really an issue and more just a curiosity. 

To clarify, the official Ubuntu 24.04 LTS ISO ships with kernel version 6.8.0.
I checked kernel.org and it appears to show that the latest LTS version is 6.6.32, which is the version used for the T2 LTS kernel.

I was just curious why the version that ships with the official Ubuntu 24.04 LTS ISO, version 6.8.0, was not used instead of the version listed as stable on kernel.org, for the Ubuntu 24.04 T2 kernel. 

Thank you again for your time and assistance in clarifying these points. I appreciate the work you and your team do for the community.

**Comment by AdityaGarg8** [comment]
> Thank you for your reply. I appreciate you taking the time to answer my questions. I should have mentioned this is not really an issue and more just a curiosity.
> 
> To clarify, the official Ubuntu 24.04 LTS ISO ships with kernel version 6.8.0. I checked kernel.org and it appears to show that the latest LTS version is 6.6.32, which is the version used for the T2 LTS kernel.
> 

LTS kernel refers to the ones referred as LTS on kernel.org. Ubuntu has changed their policy of not using LTS kernels on LTS releases from 24.04. Obviously I cannot do anything about it :). As mentioned before, I've provided the option of both LTS and Mainline kernels to the users. Use whatever you want.

> I was just curious why the version that ships with the official Ubuntu 24.04 LTS ISO, version 6.8.0, was not used instead of the version listed as stable on kernel.org, for the Ubuntu 24.04 T2 kernel.
> 
> Thank you again for your time and assistance in clarifying these points. I appreciate the work you and your team do for the community.

**Comment by maximus-sallam** [comment]
Thank you for the clarification. I'll mark this issue as closed now. Have a great day/night.
