### ISSUE TITLE
Touchbar device not found

### ISSUE THREAD

**Issue by shwwoooo** [AdityaGarg8/mbp-16.x-ubuntu-kernel#90]
Hello, I am trying to install t2 kernel to a generic Ubuntu 22.04 system. I am facing apple-ibridge build error when running `apt install linux-image...` The log file shows the following
```
/var/lib/dkms/apple-ibridge/0.1/build/apple-ibridge.c:637:35: error: initialization of ‘void (*)(struct acpi_device *)’ from incompatible pointer type ‘int (*)(struct acpi_device *)’ [-Werror=incompatible-pointer-types]
  637 |                 .remove         = appleib_remove,
      |                                   ^~~~~~~~~~~~~~
```
And when I run lsusb, I get these these devices, and touchbar is not showing up
```
Bus 007 Device 004: ID 05ac:8104 Apple, Inc. 
Bus 007 Device 003: ID 05ac:0340 Apple, Inc. Apple Internal Keyboard / Trackpad
Bus 007 Device 002: ID 05ac:8103 Apple, Inc. Headset
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 002: ID 0bda:9210 Realtek Semiconductor Corp. RTL9210 M.2 NVME Adapter
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
What should I do to solve this issue? Thanks in advance!

**Comment by AdityaGarg8** [comment]
From where have you downloaded the Touch Bar driver?

**Comment by AdityaGarg8** [comment]
And what guides are you following?

**Comment by shwwoooo** [comment]
I downloaded from the release section of this github repo. I tried 6.5 and the newest (6.9), but both did not work. I am following the the section "Download Package Manually" in this repo readme.

**Comment by AdityaGarg8** [comment]
> I downloaded from the release section of this github repo. I tried 6.5 and the newest (6.9), but both did not work. I am following the the section "Download Package Manually" in this repo readme.

What ISO have you used? And I asked from where have you downloaded the touchbar driver (DKMS one), not the kernel.

**Comment by shwwoooo** [comment]
I was using ubuntu 22.04 jammy (downloaded from ubuntu official site before). I thought the kernel comes with all the driver and most other functionalities work so I didn't manually install one for touchbar (presumably from [here](https://github.com/t2linux/apple-ib-drv)?)

**Comment by AdityaGarg8** [comment]
> I was using ubuntu 22.04 jammy (downloaded from ubuntu official site before). I thought the kernel comes with all the driver and most other functionalities work so I didn't manually install one for touchbar (presumably from [here](https://github.com/t2linux/apple-ib-drv)?)

The driver you installed no longer works on newer kernels. I assume you didn't even add the apt repo right?

**Comment by shwwoooo** [comment]
I initially tried using apt to download and install the kernel, which comes in version 6.6. I ran these commands
```
CODENAME=noble
curl -s --compressed "https://adityagarg8.github.io/t2-ubuntu-repo/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg >/dev/null
sudo curl -s --compressed -o /etc/apt/sources.list.d/t2.list "https://adityagarg8.github.io/t2-ubuntu-repo/t2.list"
echo "deb [signed-by=/etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg] https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/${CODENAME} ./" | sudo tee -a /etc/apt/sources.list.d/t2.list
sudo apt update
```
So I should have the apt repos.

**Comment by AdityaGarg8** [comment]
> I initially tried using apt to download and install the kernel, which comes in version 6.6. I ran these commands
> 
> ```
> CODENAME=noble
> curl -s --compressed "https://adityagarg8.github.io/t2-ubuntu-repo/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg >/dev/null
> sudo curl -s --compressed -o /etc/apt/sources.list.d/t2.list "https://adityagarg8.github.io/t2-ubuntu-repo/t2.list"
> echo "deb [signed-by=/etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg] https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/${CODENAME} ./" | sudo tee -a /etc/apt/sources.list.d/t2.list
> sudo apt update
> ```
> 
> So I should have the apt repos.

You are using Jammy, so use CODENAME=jammy


and you installed linux-t2-lts, which will give 6.6 kernel. You have to install linux-t2 if you want 6.9

**Comment by AdityaGarg8** [comment]
<img width="1180" alt="image" src="https://github.com/t2linux/T2-Debian-and-Ubuntu-Kernel/assets/85610623/beafb633-cffc-4bb4-9d1f-6ea963859a4c">

**Comment by AdityaGarg8** [comment]
You also have to remove the dkms driver and install `tiny-dfr` for touchbar

**Comment by AdityaGarg8** [comment]
If you need step by step help, please contact the discord. https://discord.com/invite/68MRhQu

**Comment by shwwoooo** [comment]
Sorry I copied directly from the README. Yes I used CODENAME=jammy and installed linux-t2-lts. I am fine with 6.6 kernel. I can join discord and post the solution here later. Thank you

**Comment by shwwoooo** [comment]
Hmmm, I don't know what happened exactly. I booted my mac today for the first time and it works now. It was not yesterday and I tried to reboot multiple times. Camera works now as well. Thank you for your time and prompt responses!

**Comment by shwwoooo** [comment]
Later I found out it is because of any unnormal shutdown or reboots. The devices are found when shutting down from macos and then booting linux. If I shutdown/restart/suspend from linux (screen goes black but fans are on and will rapidly spin up for a second before going off) or force shutdown by long pressing the power button, the touchbar and camera don't work.

**Comment by aes512** [comment]
> Later I found out it is because of any unnormal shutdown or reboots. The devices are found when shutting down from macos and then booting linux. If I shutdown/restart/suspend from linux (screen goes black but fans are on and will rapidly spin up for a second before going off) or force shutdown by long pressing the power button, the touchbar and camera don't work.

This happens to me every few days when my 16,1 MBP running Arch crashes. I have to reboot twice to get the touchbar recognized again. My keyboard backlight also doesn't work, but I'm not sure if that's related or not.
